# Run r cmd check
name: call-r-cmd-check
# on specifies the build triggers. See more info at https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
# The default build trigger is to run the action on every push and pull request, for any branch
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  # To run the default repository branch weekly on sunday at 6 min past midnight.
  schedule:
    - cron: '36 0 * * 0'
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/r-cmd-check.yml@main
